---
abstract: 'A Data Visualization API'
author:
  - 'Jack Maney <jack@jackmaney.com>'
build_requires:
  Cwd: 0
  Path::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hypatia
requires:
  Array::Utils: 0
  Class::Load: 0
  DBI: 0
  Data::Dumper: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Scalar::Util: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.021
